schema_version = "1.0.0"

id = "Welder"
version = "1.5.0"
name = "Welder"
tagline = "Tool for generating welds"
maintainer = "Łukasz Hoffmann"
type = "add-on"

website = "https://documentation.forgegon.com/Welder"

tags = ["Modeling"]

blender_version_min = "4.1.0"
#blender_version_max = "5.0.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
   "2016-2024 Łukasz Hoffmann"
 ]

platforms = ["windows-x64", "macos-arm64", "macos-x64", "linux-x64"]